meta_product_name: "Bookids"
meta_title: "Bookids - With Bookids, the more you read, the more you learn"
meta_description: "With Bookids, the more you read, the more you learn"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
